"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { toPlainText } from "@/lib/changelog";

interface ChangelogDisplayProps {
  changelog: string;
  repoUrl?: string;
}

function download(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ChangelogDisplay({ changelog, repoUrl }: ChangelogDisplayProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(changelog);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMd = () => download(changelog, "CHANGELOG.md", "text/markdown");
  const handleDownloadTxt = () => download(toPlainText(changelog), "CHANGELOG.txt", "text/plain");
  const handleDownloadJson = () => {
    const payload = JSON.stringify(
      { repo: repoUrl, generatedAt: new Date().toISOString(), changelog },
      null,
      2
    );
    download(payload, "changelog.json", "application/json");
  };

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between flex-wrap gap-3">
          <CardTitle>Generated Changelog</CardTitle>
          <div className="flex gap-2 flex-wrap">
            <Button variant="outline" size="sm" onClick={handleCopy}>
              {copied ? "Copied!" : "Copy"}
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownloadMd}>
              .md
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownloadTxt}>
              .txt
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownloadJson}>
              .json
            </Button>
          </div>
        </div>
        <Separator />
      </CardHeader>

      <CardContent className="text-sm leading-relaxed">
        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h1 className="text-2xl font-bold mt-6 mb-3 text-foreground">{children}</h1>
            ),
            h2: ({ children }) => (
              <h2 className="text-xl font-semibold mt-5 mb-2 text-foreground">{children}</h2>
            ),
            h3: ({ children }) => (
              <h3 className="text-base font-semibold mt-4 mb-1 text-foreground">{children}</h3>
            ),
            a: ({ href, children }) => (
              <a
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary hover:underline"
              >
                {children}
              </a>
            ),
            ul: ({ children }) => (
              <ul className="list-disc pl-5 space-y-1 my-2">{children}</ul>
            ),
            li: ({ children }) => <li className="text-muted-foreground">{children}</li>,
            p: ({ children }) => <p className="my-2 text-muted-foreground">{children}</p>,
            strong: ({ children }) => (
              <strong className="font-semibold text-foreground">{children}</strong>
            ),
            hr: () => <Separator className="my-4" />,
          }}
        >
          {changelog}
        </ReactMarkdown>

        <p className="text-xs text-muted-foreground/50 text-right mt-4">
          Generated by Gemini 2.5 Flash (Google AI)
        </p>
      </CardContent>
    </Card>
  );
}
