"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { toPlainText } from "@/lib/changelog";

interface ChangelogDisplayProps {
  changelog: string;
  repoUrl?: string;
}

function download(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ChangelogDisplay({ changelog, repoUrl }: ChangelogDisplayProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(changelog);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMd = () => download(changelog, "CHANGELOG.md", "text/markdown");

  const handleDownloadTxt = () =>
    download(toPlainText(changelog), "CHANGELOG.txt", "text/plain");

  const handleDownloadJson = () => {
    const payload = JSON.stringify(
      { repo: repoUrl, generatedAt: new Date().toISOString(), changelog },
      null,
      2
    );
    download(payload, "changelog.json", "application/json");
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <h2 className="text-lg font-semibold">Generated Changelog</h2>
        <div className="flex gap-2 flex-wrap">
          <button
            onClick={handleCopy}
            className="px-4 py-2 text-sm bg-gray-800 hover:bg-gray-700 rounded-lg transition-colors"
          >
            {copied ? "Copied!" : "Copy"}
          </button>
          <button
            onClick={handleDownloadMd}
            className="px-4 py-2 text-sm bg-gray-800 hover:bg-gray-700 rounded-lg transition-colors"
          >
            .md
          </button>
          <button
            onClick={handleDownloadTxt}
            className="px-4 py-2 text-sm bg-gray-800 hover:bg-gray-700 rounded-lg transition-colors"
          >
            .txt
          </button>
          <button
            onClick={handleDownloadJson}
            className="px-4 py-2 text-sm bg-gray-800 hover:bg-gray-700 rounded-lg transition-colors"
          >
            .json
          </button>
        </div>
      </div>

      <div className="bg-gray-900 border border-gray-800 rounded-lg p-6 text-sm text-gray-200 leading-relaxed">
        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h1 className="text-2xl font-bold mt-6 mb-3 text-white">{children}</h1>
            ),
            h2: ({ children }) => (
              <h2 className="text-xl font-semibold mt-5 mb-2 text-white">{children}</h2>
            ),
            h3: ({ children }) => (
              <h3 className="text-base font-semibold mt-4 mb-1 text-gray-100">{children}</h3>
            ),
            a: ({ href, children }) => (
              <a
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-400 hover:underline"
              >
                {children}
              </a>
            ),
            ul: ({ children }) => (
              <ul className="list-disc pl-5 space-y-1 my-2">{children}</ul>
            ),
            li: ({ children }) => <li className="text-gray-300">{children}</li>,
            p: ({ children }) => <p className="my-2 text-gray-300">{children}</p>,
            strong: ({ children }) => (
              <strong className="font-semibold text-white">{children}</strong>
            ),
            hr: () => <hr className="border-gray-700 my-4" />,
          }}
        >
          {changelog}
        </ReactMarkdown>
      </div>

      <p className="text-xs text-gray-600 text-right">
        Generated by Gemini 2.5 Flash (Google AI)
      </p>
    </div>
  );
}
